services:
    yt-dlp-api:
        depends_on:
            - redis
        image: ${DOCKERHUB_USERNAME}/yt-dlp-api:${IMAGE_TAG}
        container_name: yt-dlp-api-prod
        ports:
            - "3000:3000"
        restart: always
        environment:
            - NODE_ENV=production
        volumes:
            - ~/.env.prod:/api/.env
            - ~/www.youtube.com_cookies.txt:/api/www.youtube.com_cookies.txt
    redis:
        image: redis:alpine
        container_name: redis-prod
        restart: always
        # No need to expose the port to the internet. Redis can already talk to the server internally
